### Generated by rprotoc. DO NOT EDIT!
### <proto file: rpc.proto>
# package demo;
# 
# message SearchRequest {
#   required string keyword = 1;
# }
# 
# message SearchResponse {
#   required string result = 1;
# }
# 
# service RpcService {
#   rpc Search (SearchRequest) returns (SearchResponse);
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Demo
  class SearchRequest < ::Protobuf::Message
    defined_in __FILE__
    required :string, :keyword, 1
  end
  class SearchResponse < ::Protobuf::Message
    defined_in __FILE__
    required :string, :result, 1
  end
end